"""Regenerate ``data.js`` for the guide page from the example's own encoder.

Run from the repository root (no radio needed):

    python -m guide.build_data

For every MCS it encodes one datagram of each payload size and records the
number of payload OFDM symbols, so the page never re-derives FEC block sizes.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from ofdm_link.phy.mcs_table import MCS_TABLE, describe_mcs_entry
from ofdm_message_link import datagram, options
from ofdm_message_link.dashboard import MARGIN_DB, SNR_THRESHOLD_DB
from ofdm_message_link.link import MessageTransmitter

FIXED_SYMBOLS = 5  # preamble, training and three header symbols


def main() -> None:
    table = []
    for entry in MCS_TABLE:
        parser = argparse.ArgumentParser()
        options.add_common_arguments(parser)
        resolved = options.resolve(parser.parse_args(["--mcs-index", str(entry.index)]))
        phy = resolved.config.phy
        symbol_len = phy.fft_len + phy.cyclic_prefix_len
        max_payload = resolved.profile.max_message_payload_bytes
        transmitter = MessageTransmitter(resolved.profile, mcs_entry=resolved.mcs_entry)
        symbols = []
        for size in range(1, max_payload + 1):
            (burst,) = transmitter.encode_message(bytes(size))
            body = burst.sample_count - 2 * resolved.profile.guard_samples
            assert body % symbol_len == 0, (entry.index, size, burst.sample_count)
            symbols.append(body // symbol_len - FIXED_SYMBOLS)
        # Run-length encode: [first payload size, payload symbols] per step.
        steps = [[1, symbols[0]]]
        for size, count in enumerate(symbols[1:], start=2):
            if count != steps[-1][1]:
                steps.append([size, count])
        table.append(
            {
                "index": entry.index,
                "label": describe_mcs_entry(entry),
                "snrThresholdDb": SNR_THRESHOLD_DB.get(entry.index),
                "steps": steps,
            }
        )
    data = {
        "sampleRate": float(phy.sample_rate),
        "fftLen": phy.fft_len,
        "cpLen": phy.cyclic_prefix_len,
        "guardSamples": resolved.profile.guard_samples,
        "fixedSymbols": FIXED_SYMBOLS,
        "datagramHeaderBytes": datagram.HEADER_SIZE,
        "maxFragmentBytes": max_payload,
        "marginDb": MARGIN_DB,
        "mcs": table,
    }
    out = Path(__file__).with_name("data.js")
    out.write_text(
        "// Generated by build_data.py from the example's encoder. Do not edit.\n"
        "window.GUIDE_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
